server:
  port: 8189
  servlet:
    context-path: /atm

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=atm
    username: postgres
    password: 190283

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false

  thymeleaf:
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
  jackson:
    serialization:
      indent_output: true